# Generated by Django 3.2.4 on 2021-11-10 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('password', models.CharField(max_length=100, verbose_name='登陆密码')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('isadmin', models.IntegerField(default=0, verbose_name='是否管理员')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('updater', models.CharField(max_length=20, null=True, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'userinfo',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('token', models.CharField(max_length=50, verbose_name='token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='k_user.userinfo')),
            ],
            options={
                'verbose_name': '用户登陆token',
                'db_table': 'usertoken',
            },
        ),
    ]
